---
title: "MMMILC Summary Report"
subtitle: "\"To understand the heart and mind of a person, look not at what he has already achieved, but at what he aspires to do.\" -Kahlil Gibran"
subtitle2: "\"Jump, and you will find out how to unfold your wings as you fall.\" -Ray Bradbury" 
subtitle3: "\"Trust thyself.\" -Ralph Waldo Emerson"
output: pdf_document
date: '`r Sys.time()`'
---

```{r, echo = FALSE}
#overall and last weeks summary statistics
kable(summStats, caption = "Summary Statistics", digits = 2)
```

```{r, echo = FALSE}
#status table for milkweeds
kable(status.table, caption = "Milkweed Status")
```

```{r, echo = FALSE}
#rank table for top 10 students
kable(rankTable, caption = "Student Summary")
```

```{r, echo = FALSE, message = FALSE, warning=FALSE}
#print the summary plots together in a grid
do.call(grid.arrange, c(weekSummPlots))

```
```{r, echo = FALSE, message = FALSE, warning=FALSE}
#print the two time plots
do.call(grid.arrange, c(timePlots))

```
```{r, echo = FALSE, message = FALSE, warning=FALSE}
#print the two big plots
p7
p8.1
p8.2

```

